/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 109
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 64
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 14
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 18
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_COLON = 2,
  sym_frontmatter_key = 3,
  anon_sym_Feature_COLON = 4,
  sym_feature_name = 5,
  anon_sym_Provides_COLON = 6,
  anon_sym_Consumes_COLON = 7,
  anon_sym_Invariants_COLON = 8,
  anon_sym_OutOfScope_COLON = 9,
  anon_sym_DASH = 10,
  anon_sym_DOT = 11,
  anon_sym_ATsource = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  aux_sym_entry_description_token1 = 15,
  anon_sym_Scenario = 16,
  sym_scenario_kind = 17,
  anon_sym_Given = 18,
  anon_sym_When = 19,
  anon_sym_Then = 20,
  anon_sym_And = 21,
  anon_sym_But = 22,
  sym_iso_date = 23,
  sym_quoted_string = 24,
  anon_sym_LBRACK = 25,
  anon_sym_COMMA = 26,
  anon_sym_RBRACK = 27,
  sym_comment = 28,
  anon_sym_LF = 29,
  sym_source_file = 30,
  sym_frontmatter = 31,
  sym_frontmatter_entry = 32,
  sym__frontmatter_value = 33,
  sym_feature = 34,
  sym__context_block = 35,
  sym_provides_block = 36,
  sym_consumes_block = 37,
  sym_invariants_block = 38,
  sym_out_of_scope_block = 39,
  sym_handle_entry = 40,
  sym__handle = 41,
  sym_prefixed_handle = 42,
  sym_path_handle = 43,
  sym_identifier_path = 44,
  sym_source_anchor = 45,
  sym_entry_description = 46,
  sym_prose_entry = 47,
  sym_prose_text = 48,
  sym_scenario_block = 49,
  sym_scenario_name = 50,
  sym_step = 51,
  sym_step_keyword = 52,
  sym_step_text = 53,
  sym_list = 54,
  aux_sym__blank_lines = 55,
  aux_sym_frontmatter_repeat1 = 56,
  aux_sym_feature_repeat1 = 57,
  aux_sym_feature_repeat2 = 58,
  aux_sym_provides_block_repeat1 = 59,
  aux_sym_invariants_block_repeat1 = 60,
  aux_sym_identifier_path_repeat1 = 61,
  aux_sym_scenario_block_repeat1 = 62,
  aux_sym_list_repeat1 = 63,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_COLON] = ":",
  [sym_frontmatter_key] = "frontmatter_key",
  [anon_sym_Feature_COLON] = "Feature:",
  [sym_feature_name] = "feature_name",
  [anon_sym_Provides_COLON] = "Provides:",
  [anon_sym_Consumes_COLON] = "Consumes:",
  [anon_sym_Invariants_COLON] = "Invariants:",
  [anon_sym_OutOfScope_COLON] = "OutOfScope:",
  [anon_sym_DASH] = "-",
  [anon_sym_DOT] = ".",
  [anon_sym_ATsource] = "@source",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [aux_sym_entry_description_token1] = "entry_description_token1",
  [anon_sym_Scenario] = "Scenario",
  [sym_scenario_kind] = "scenario_kind",
  [anon_sym_Given] = "Given",
  [anon_sym_When] = "When",
  [anon_sym_Then] = "Then",
  [anon_sym_And] = "And",
  [anon_sym_But] = "But",
  [sym_iso_date] = "iso_date",
  [sym_quoted_string] = "quoted_string",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [sym_comment] = "comment",
  [anon_sym_LF] = "\n",
  [sym_source_file] = "source_file",
  [sym_frontmatter] = "frontmatter",
  [sym_frontmatter_entry] = "frontmatter_entry",
  [sym__frontmatter_value] = "_frontmatter_value",
  [sym_feature] = "feature",
  [sym__context_block] = "_context_block",
  [sym_provides_block] = "provides_block",
  [sym_consumes_block] = "consumes_block",
  [sym_invariants_block] = "invariants_block",
  [sym_out_of_scope_block] = "out_of_scope_block",
  [sym_handle_entry] = "handle_entry",
  [sym__handle] = "_handle",
  [sym_prefixed_handle] = "prefixed_handle",
  [sym_path_handle] = "path_handle",
  [sym_identifier_path] = "identifier_path",
  [sym_source_anchor] = "source_anchor",
  [sym_entry_description] = "entry_description",
  [sym_prose_entry] = "prose_entry",
  [sym_prose_text] = "prose_text",
  [sym_scenario_block] = "scenario_block",
  [sym_scenario_name] = "scenario_name",
  [sym_step] = "step",
  [sym_step_keyword] = "step_keyword",
  [sym_step_text] = "step_text",
  [sym_list] = "list",
  [aux_sym__blank_lines] = "_blank_lines",
  [aux_sym_frontmatter_repeat1] = "frontmatter_repeat1",
  [aux_sym_feature_repeat1] = "feature_repeat1",
  [aux_sym_feature_repeat2] = "feature_repeat2",
  [aux_sym_provides_block_repeat1] = "provides_block_repeat1",
  [aux_sym_invariants_block_repeat1] = "invariants_block_repeat1",
  [aux_sym_identifier_path_repeat1] = "identifier_path_repeat1",
  [aux_sym_scenario_block_repeat1] = "scenario_block_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_frontmatter_key] = sym_frontmatter_key,
  [anon_sym_Feature_COLON] = anon_sym_Feature_COLON,
  [sym_feature_name] = sym_feature_name,
  [anon_sym_Provides_COLON] = anon_sym_Provides_COLON,
  [anon_sym_Consumes_COLON] = anon_sym_Consumes_COLON,
  [anon_sym_Invariants_COLON] = anon_sym_Invariants_COLON,
  [anon_sym_OutOfScope_COLON] = anon_sym_OutOfScope_COLON,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_ATsource] = anon_sym_ATsource,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_entry_description_token1] = aux_sym_entry_description_token1,
  [anon_sym_Scenario] = anon_sym_Scenario,
  [sym_scenario_kind] = sym_scenario_kind,
  [anon_sym_Given] = anon_sym_Given,
  [anon_sym_When] = anon_sym_When,
  [anon_sym_Then] = anon_sym_Then,
  [anon_sym_And] = anon_sym_And,
  [anon_sym_But] = anon_sym_But,
  [sym_iso_date] = sym_iso_date,
  [sym_quoted_string] = sym_quoted_string,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_comment] = sym_comment,
  [anon_sym_LF] = anon_sym_LF,
  [sym_source_file] = sym_source_file,
  [sym_frontmatter] = sym_frontmatter,
  [sym_frontmatter_entry] = sym_frontmatter_entry,
  [sym__frontmatter_value] = sym__frontmatter_value,
  [sym_feature] = sym_feature,
  [sym__context_block] = sym__context_block,
  [sym_provides_block] = sym_provides_block,
  [sym_consumes_block] = sym_consumes_block,
  [sym_invariants_block] = sym_invariants_block,
  [sym_out_of_scope_block] = sym_out_of_scope_block,
  [sym_handle_entry] = sym_handle_entry,
  [sym__handle] = sym__handle,
  [sym_prefixed_handle] = sym_prefixed_handle,
  [sym_path_handle] = sym_path_handle,
  [sym_identifier_path] = sym_identifier_path,
  [sym_source_anchor] = sym_source_anchor,
  [sym_entry_description] = sym_entry_description,
  [sym_prose_entry] = sym_prose_entry,
  [sym_prose_text] = sym_prose_text,
  [sym_scenario_block] = sym_scenario_block,
  [sym_scenario_name] = sym_scenario_name,
  [sym_step] = sym_step,
  [sym_step_keyword] = sym_step_keyword,
  [sym_step_text] = sym_step_text,
  [sym_list] = sym_list,
  [aux_sym__blank_lines] = aux_sym__blank_lines,
  [aux_sym_frontmatter_repeat1] = aux_sym_frontmatter_repeat1,
  [aux_sym_feature_repeat1] = aux_sym_feature_repeat1,
  [aux_sym_feature_repeat2] = aux_sym_feature_repeat2,
  [aux_sym_provides_block_repeat1] = aux_sym_provides_block_repeat1,
  [aux_sym_invariants_block_repeat1] = aux_sym_invariants_block_repeat1,
  [aux_sym_identifier_path_repeat1] = aux_sym_identifier_path_repeat1,
  [aux_sym_scenario_block_repeat1] = aux_sym_scenario_block_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_frontmatter_key] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Feature_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_feature_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Provides_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Consumes_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Invariants_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OutOfScope_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATsource] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_entry_description_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_Scenario] = {
    .visible = true,
    .named = false,
  },
  [sym_scenario_kind] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Given] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_When] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_And] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_But] = {
    .visible = true,
    .named = false,
  },
  [sym_iso_date] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_frontmatter] = {
    .visible = true,
    .named = true,
  },
  [sym_frontmatter_entry] = {
    .visible = true,
    .named = true,
  },
  [sym__frontmatter_value] = {
    .visible = false,
    .named = true,
  },
  [sym_feature] = {
    .visible = true,
    .named = true,
  },
  [sym__context_block] = {
    .visible = false,
    .named = true,
  },
  [sym_provides_block] = {
    .visible = true,
    .named = true,
  },
  [sym_consumes_block] = {
    .visible = true,
    .named = true,
  },
  [sym_invariants_block] = {
    .visible = true,
    .named = true,
  },
  [sym_out_of_scope_block] = {
    .visible = true,
    .named = true,
  },
  [sym_handle_entry] = {
    .visible = true,
    .named = true,
  },
  [sym__handle] = {
    .visible = false,
    .named = true,
  },
  [sym_prefixed_handle] = {
    .visible = true,
    .named = true,
  },
  [sym_path_handle] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier_path] = {
    .visible = true,
    .named = true,
  },
  [sym_source_anchor] = {
    .visible = true,
    .named = true,
  },
  [sym_entry_description] = {
    .visible = true,
    .named = true,
  },
  [sym_prose_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_prose_text] = {
    .visible = true,
    .named = true,
  },
  [sym_scenario_block] = {
    .visible = true,
    .named = true,
  },
  [sym_scenario_name] = {
    .visible = true,
    .named = true,
  },
  [sym_step] = {
    .visible = true,
    .named = true,
  },
  [sym_step_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_step_text] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__blank_lines] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_frontmatter_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_feature_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_feature_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_provides_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_invariants_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_path_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scenario_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_description = 1,
  field_feature = 2,
  field_frontmatter = 3,
  field_handle = 4,
  field_key = 5,
  field_keyword = 6,
  field_kind = 7,
  field_name = 8,
  field_path = 9,
  field_prefix = 10,
  field_source_anchor = 11,
  field_summary = 12,
  field_text = 13,
  field_value = 14,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_description] = "description",
  [field_feature] = "feature",
  [field_frontmatter] = "frontmatter",
  [field_handle] = "handle",
  [field_key] = "key",
  [field_keyword] = "keyword",
  [field_kind] = "kind",
  [field_name] = "name",
  [field_path] = "path",
  [field_prefix] = "prefix",
  [field_source_anchor] = "source_anchor",
  [field_summary] = "summary",
  [field_text] = "text",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 2},
  [8] = {.index = 12, .length = 1},
  [9] = {.index = 13, .length = 1},
  [10] = {.index = 14, .length = 2},
  [11] = {.index = 16, .length = 2},
  [12] = {.index = 18, .length = 1},
  [13] = {.index = 19, .length = 2},
  [14] = {.index = 21, .length = 3},
  [15] = {.index = 24, .length = 2},
  [16] = {.index = 26, .length = 1},
  [17] = {.index = 27, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_feature, 0},
  [1] =
    {field_feature, 1},
    {field_frontmatter, 0},
  [3] =
    {field_feature, 1},
  [4] =
    {field_key, 0},
    {field_value, 2},
  [6] =
    {field_name, 1},
    {field_summary, 2},
  [8] =
    {field_feature, 2},
    {field_frontmatter, 1},
  [10] =
    {field_name, 1},
    {field_summary, 3},
  [12] =
    {field_handle, 1},
  [13] =
    {field_text, 1},
  [14] =
    {field_handle, 1},
    {field_source_anchor, 2},
  [16] =
    {field_description, 2},
    {field_handle, 1},
  [18] =
    {field_name, 2},
  [19] =
    {field_path, 2},
    {field_prefix, 0},
  [21] =
    {field_description, 3},
    {field_handle, 1},
    {field_source_anchor, 2},
  [24] =
    {field_keyword, 0},
    {field_text, 1},
  [26] =
    {field_value, 2},
  [27] =
    {field_kind, 2},
    {field_name, 5},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(30);
      ADVANCE_MAP(
        '\n', 114,
        '"', 6,
        '#', 113,
        '(', 50,
        ')', 51,
        ',', 111,
        '-', 46,
        '.', 47,
        ':', 31,
        '@', 16,
        'C', 89,
        'F', 76,
        'I', 85,
        'O', 102,
        'P', 92,
        '[', 110,
        ']', 112,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(114);
      if (lookahead == '#') ADVANCE(113);
      if (lookahead == '.') ADVANCE(47);
      if (lookahead == ':') ADVANCE(31);
      if (lookahead == '@') ADVANCE(61);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(114);
      if (lookahead == '#') ADVANCE(113);
      if (lookahead == '.') ADVANCE(47);
      if (lookahead == '@') ADVANCE(61);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(114);
      if (lookahead == '#') ADVANCE(113);
      if (lookahead == '@') ADVANCE(26);
      if (lookahead == 'F') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(114);
      if (lookahead == '#') ADVANCE(113);
      if (lookahead == '@') ADVANCE(61);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(54);
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(114);
      if (lookahead == '#') ADVANCE(113);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(109);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(113);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 8:
      if (lookahead == '#') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(41);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(25);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(38);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 16:
      if (lookahead == 's') ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 18:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(108);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 26:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 27:
      if (eof) ADVANCE(30);
      ADVANCE_MAP(
        '\n', 114,
        '"', 6,
        '#', 113,
        '-', 46,
        '@', 26,
        'C', 89,
        'F', 76,
        'I', 85,
        'O', 102,
        'P', 92,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 28:
      if (eof) ADVANCE(30);
      if (lookahead == '\n') ADVANCE(114);
      if (lookahead == '"') ADVANCE(6);
      if (lookahead == '#') ADVANCE(113);
      if (lookahead == '[') ADVANCE(110);
      if (lookahead == ']') ADVANCE(112);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 29:
      if (eof) ADVANCE(30);
      if (lookahead == '\n') ADVANCE(114);
      if (lookahead == '#') ADVANCE(113);
      if (lookahead == '-') ADVANCE(46);
      if (lookahead == 'C') ADVANCE(89);
      if (lookahead == 'I') ADVANCE(85);
      if (lookahead == 'O') ADVANCE(102);
      if (lookahead == 'P') ADVANCE(92);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_frontmatter_key);
      if (lookahead == 'c') ADVANCE(33);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_frontmatter_key);
      if (lookahead == 'e') ADVANCE(49);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_frontmatter_key);
      if (lookahead == 'o') ADVANCE(36);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_frontmatter_key);
      if (lookahead == 'r') ADVANCE(32);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_frontmatter_key);
      if (lookahead == 'u') ADVANCE(35);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_frontmatter_key);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_Feature_COLON);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_feature_name);
      if (lookahead == '"') ADVANCE(113);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_feature_name);
      if (lookahead == '#') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_feature_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_Provides_COLON);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_Consumes_COLON);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_Invariants_COLON);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_OutOfScope_COLON);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_ATsource);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_ATsource);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_entry_description_token1);
      if (lookahead == '\n') ADVANCE(114);
      if (lookahead == '#') ADVANCE(113);
      if (lookahead == '.') ADVANCE(47);
      if (lookahead == ':') ADVANCE(31);
      if (lookahead == '@') ADVANCE(61);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_entry_description_token1);
      if (lookahead == '\n') ADVANCE(114);
      if (lookahead == '#') ADVANCE(113);
      if (lookahead == '.') ADVANCE(47);
      if (lookahead == '@') ADVANCE(61);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_entry_description_token1);
      if (lookahead == '\n') ADVANCE(114);
      if (lookahead == '#') ADVANCE(113);
      if (lookahead == '@') ADVANCE(61);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(54);
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_entry_description_token1);
      if (lookahead == '\n') ADVANCE(114);
      if (lookahead == '#') ADVANCE(113);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_entry_description_token1);
      if (lookahead == '#') ADVANCE(113);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_entry_description_token1);
      if (lookahead == 'c') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_entry_description_token1);
      if (lookahead == 'e') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_entry_description_token1);
      if (lookahead == 'o') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_entry_description_token1);
      if (lookahead == 'r') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_entry_description_token1);
      if (lookahead == 's') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_entry_description_token1);
      if (lookahead == 'u') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_entry_description_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(38);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(43);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(42);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(44);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(45);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O') ADVANCE(81);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S') ADVANCE(74);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(93);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(100);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(80);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(72);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(64);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(96);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(68);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(97);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(75);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(73);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(78);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(106);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(95);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(101);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(91);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(86);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(105);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(79);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(90);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(83);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(77);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(103);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(65);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(66);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(67);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(69);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(104);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(98);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(99);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(84);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(94);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'v') ADVANCE(82);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'v') ADVANCE(71);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_iso_date);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_quoted_string);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'A') ADVANCE(1);
      if (lookahead == 'B') ADVANCE(2);
      if (lookahead == 'G') ADVANCE(3);
      if (lookahead == 'S') ADVANCE(4);
      if (lookahead == 'T') ADVANCE(5);
      if (lookahead == 'W') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'i') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'c') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'h') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'h') ADVANCE(13);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_scenario_kind);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 10:
      if (lookahead == 'v') ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_And);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_But);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_Then);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_When);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_Given);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_Scenario);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 3},
  [2] = {.lex_state = 27},
  [3] = {.lex_state = 29},
  [4] = {.lex_state = 29},
  [5] = {.lex_state = 29},
  [6] = {.lex_state = 29},
  [7] = {.lex_state = 29},
  [8] = {.lex_state = 28},
  [9] = {.lex_state = 28},
  [10] = {.lex_state = 28},
  [11] = {.lex_state = 29},
  [12] = {.lex_state = 28},
  [13] = {.lex_state = 29},
  [14] = {.lex_state = 29},
  [15] = {.lex_state = 29},
  [16] = {.lex_state = 29},
  [17] = {.lex_state = 29},
  [18] = {.lex_state = 28},
  [19] = {.lex_state = 29},
  [20] = {.lex_state = 28},
  [21] = {.lex_state = 29},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 28},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 28},
  [27] = {.lex_state = 28},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 28},
  [30] = {.lex_state = 28},
  [31] = {.lex_state = 28},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 28},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 5},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 28},
  [62] = {.lex_state = 7},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 28},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 28},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 7},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 7},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 3},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 7},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 5},
  [83] = {.lex_state = 28},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 28},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 7},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 8},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 28},
  [107] = {.lex_state = 28},
  [108] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_frontmatter_key] = ACTIONS(1),
    [anon_sym_Feature_COLON] = ACTIONS(1),
    [anon_sym_Provides_COLON] = ACTIONS(1),
    [anon_sym_Consumes_COLON] = ACTIONS(1),
    [anon_sym_Invariants_COLON] = ACTIONS(1),
    [anon_sym_OutOfScope_COLON] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_ATsource] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_Scenario] = ACTIONS(1),
    [sym_scenario_kind] = ACTIONS(1),
    [anon_sym_Given] = ACTIONS(1),
    [anon_sym_When] = ACTIONS(1),
    [anon_sym_Then] = ACTIONS(1),
    [anon_sym_And] = ACTIONS(1),
    [anon_sym_But] = ACTIONS(1),
    [sym_iso_date] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(90),
    [sym_frontmatter] = STATE(77),
    [sym_frontmatter_entry] = STATE(75),
    [sym_feature] = STATE(43),
    [aux_sym__blank_lines] = STATE(22),
    [aux_sym_frontmatter_repeat1] = STATE(41),
    [sym_frontmatter_key] = ACTIONS(5),
    [anon_sym_Feature_COLON] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    ACTIONS(11), 15,
      ts_builtin_sym_end,
      sym_frontmatter_key,
      anon_sym_Feature_COLON,
      anon_sym_Provides_COLON,
      anon_sym_Consumes_COLON,
      anon_sym_Invariants_COLON,
      anon_sym_OutOfScope_COLON,
      anon_sym_DASH,
      anon_sym_Scenario,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      sym_quoted_string,
  [27] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(16), 1,
      ts_builtin_sym_end,
    ACTIONS(18), 1,
      anon_sym_Provides_COLON,
    ACTIONS(20), 1,
      anon_sym_Consumes_COLON,
    ACTIONS(22), 1,
      anon_sym_Invariants_COLON,
    ACTIONS(24), 1,
      anon_sym_OutOfScope_COLON,
    ACTIONS(26), 1,
      anon_sym_Scenario,
    ACTIONS(28), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    STATE(27), 2,
      sym_scenario_block,
      aux_sym_feature_repeat2,
    STATE(5), 6,
      sym__context_block,
      sym_provides_block,
      sym_consumes_block,
      sym_invariants_block,
      sym_out_of_scope_block,
      aux_sym_feature_repeat1,
  [67] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(18), 1,
      anon_sym_Provides_COLON,
    ACTIONS(20), 1,
      anon_sym_Consumes_COLON,
    ACTIONS(22), 1,
      anon_sym_Invariants_COLON,
    ACTIONS(24), 1,
      anon_sym_OutOfScope_COLON,
    ACTIONS(26), 1,
      anon_sym_Scenario,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(33), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    STATE(31), 2,
      sym_scenario_block,
      aux_sym_feature_repeat2,
    STATE(6), 6,
      sym__context_block,
      sym_provides_block,
      sym_consumes_block,
      sym_invariants_block,
      sym_out_of_scope_block,
      aux_sym_feature_repeat1,
  [107] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(18), 1,
      anon_sym_Provides_COLON,
    ACTIONS(20), 1,
      anon_sym_Consumes_COLON,
    ACTIONS(22), 1,
      anon_sym_Invariants_COLON,
    ACTIONS(24), 1,
      anon_sym_OutOfScope_COLON,
    ACTIONS(26), 1,
      anon_sym_Scenario,
    ACTIONS(36), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(29), 2,
      sym_scenario_block,
      aux_sym_feature_repeat2,
    STATE(7), 6,
      sym__context_block,
      sym_provides_block,
      sym_consumes_block,
      sym_invariants_block,
      sym_out_of_scope_block,
      aux_sym_feature_repeat1,
  [142] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(18), 1,
      anon_sym_Provides_COLON,
    ACTIONS(20), 1,
      anon_sym_Consumes_COLON,
    ACTIONS(22), 1,
      anon_sym_Invariants_COLON,
    ACTIONS(24), 1,
      anon_sym_OutOfScope_COLON,
    ACTIONS(26), 1,
      anon_sym_Scenario,
    ACTIONS(38), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(26), 2,
      sym_scenario_block,
      aux_sym_feature_repeat2,
    STATE(7), 6,
      sym__context_block,
      sym_provides_block,
      sym_consumes_block,
      sym_invariants_block,
      sym_out_of_scope_block,
      aux_sym_feature_repeat1,
  [177] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      anon_sym_Provides_COLON,
    ACTIONS(45), 1,
      anon_sym_Consumes_COLON,
    ACTIONS(48), 1,
      anon_sym_Invariants_COLON,
    ACTIONS(51), 1,
      anon_sym_OutOfScope_COLON,
    ACTIONS(40), 3,
      ts_builtin_sym_end,
      anon_sym_Scenario,
      anon_sym_LF,
    STATE(7), 6,
      sym__context_block,
      sym_provides_block,
      sym_consumes_block,
      sym_invariants_block,
      sym_out_of_scope_block,
      aux_sym_feature_repeat1,
  [206] = 6,
    ACTIONS(3), 1,
      sym_comment,
    STATE(10), 1,
      aux_sym_scenario_block_repeat1,
    STATE(70), 1,
      sym_step,
    STATE(71), 1,
      sym_step_keyword,
    ACTIONS(54), 3,
      ts_builtin_sym_end,
      anon_sym_Scenario,
      anon_sym_LF,
    ACTIONS(56), 5,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
  [231] = 6,
    ACTIONS(3), 1,
      sym_comment,
    STATE(10), 1,
      aux_sym_scenario_block_repeat1,
    STATE(70), 1,
      sym_step,
    STATE(71), 1,
      sym_step_keyword,
    ACTIONS(58), 3,
      ts_builtin_sym_end,
      anon_sym_Scenario,
      anon_sym_LF,
    ACTIONS(56), 5,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
  [256] = 6,
    ACTIONS(3), 1,
      sym_comment,
    STATE(10), 1,
      aux_sym_scenario_block_repeat1,
    STATE(70), 1,
      sym_step,
    STATE(71), 1,
      sym_step_keyword,
    ACTIONS(60), 3,
      ts_builtin_sym_end,
      anon_sym_Scenario,
      anon_sym_LF,
    ACTIONS(62), 5,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
  [281] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_DASH,
    STATE(16), 1,
      aux_sym_provides_block_repeat1,
    STATE(78), 1,
      sym_handle_entry,
    ACTIONS(65), 7,
      ts_builtin_sym_end,
      anon_sym_Provides_COLON,
      anon_sym_Consumes_COLON,
      anon_sym_Invariants_COLON,
      anon_sym_OutOfScope_COLON,
      anon_sym_Scenario,
      anon_sym_LF,
  [303] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    STATE(8), 1,
      aux_sym_scenario_block_repeat1,
    STATE(70), 1,
      sym_step,
    STATE(71), 1,
      sym_step_keyword,
    ACTIONS(56), 5,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
  [329] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_DASH,
    STATE(15), 1,
      aux_sym_invariants_block_repeat1,
    STATE(63), 1,
      sym_prose_entry,
    ACTIONS(71), 7,
      ts_builtin_sym_end,
      anon_sym_Provides_COLON,
      anon_sym_Consumes_COLON,
      anon_sym_Invariants_COLON,
      anon_sym_OutOfScope_COLON,
      anon_sym_Scenario,
      anon_sym_LF,
  [351] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_DASH,
    STATE(15), 1,
      aux_sym_invariants_block_repeat1,
    STATE(63), 1,
      sym_prose_entry,
    ACTIONS(75), 7,
      ts_builtin_sym_end,
      anon_sym_Provides_COLON,
      anon_sym_Consumes_COLON,
      anon_sym_Invariants_COLON,
      anon_sym_OutOfScope_COLON,
      anon_sym_Scenario,
      anon_sym_LF,
  [373] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_DASH,
    STATE(15), 1,
      aux_sym_invariants_block_repeat1,
    STATE(63), 1,
      sym_prose_entry,
    ACTIONS(77), 7,
      ts_builtin_sym_end,
      anon_sym_Provides_COLON,
      anon_sym_Consumes_COLON,
      anon_sym_Invariants_COLON,
      anon_sym_OutOfScope_COLON,
      anon_sym_Scenario,
      anon_sym_LF,
  [395] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_DASH,
    STATE(16), 1,
      aux_sym_provides_block_repeat1,
    STATE(78), 1,
      sym_handle_entry,
    ACTIONS(82), 7,
      ts_builtin_sym_end,
      anon_sym_Provides_COLON,
      anon_sym_Consumes_COLON,
      anon_sym_Invariants_COLON,
      anon_sym_OutOfScope_COLON,
      anon_sym_Scenario,
      anon_sym_LF,
  [417] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_DASH,
    STATE(16), 1,
      aux_sym_provides_block_repeat1,
    STATE(78), 1,
      sym_handle_entry,
    ACTIONS(87), 7,
      ts_builtin_sym_end,
      anon_sym_Provides_COLON,
      anon_sym_Consumes_COLON,
      anon_sym_Invariants_COLON,
      anon_sym_OutOfScope_COLON,
      anon_sym_Scenario,
      anon_sym_LF,
  [439] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    STATE(9), 1,
      aux_sym_scenario_block_repeat1,
    STATE(70), 1,
      sym_step,
    STATE(71), 1,
      sym_step_keyword,
    ACTIONS(56), 5,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
  [465] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    ACTIONS(82), 7,
      ts_builtin_sym_end,
      anon_sym_Provides_COLON,
      anon_sym_Consumes_COLON,
      anon_sym_Invariants_COLON,
      anon_sym_OutOfScope_COLON,
      anon_sym_DASH,
      anon_sym_Scenario,
  [484] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    ACTIONS(60), 7,
      ts_builtin_sym_end,
      anon_sym_Scenario,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
  [503] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    ACTIONS(77), 7,
      ts_builtin_sym_end,
      anon_sym_Provides_COLON,
      anon_sym_Consumes_COLON,
      anon_sym_Invariants_COLON,
      anon_sym_OutOfScope_COLON,
      anon_sym_DASH,
      anon_sym_Scenario,
  [522] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_frontmatter_key,
    ACTIONS(7), 1,
      anon_sym_Feature_COLON,
    ACTIONS(69), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    STATE(41), 1,
      aux_sym_frontmatter_repeat1,
    STATE(46), 1,
      sym_feature,
    STATE(66), 1,
      sym_frontmatter,
    STATE(75), 1,
      sym_frontmatter_entry,
  [550] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_LBRACK,
    STATE(92), 2,
      sym__frontmatter_value,
      sym_list,
    ACTIONS(98), 3,
      sym_identifier,
      sym_iso_date,
      sym_quoted_string,
  [566] = 5,
    ACTIONS(102), 1,
      anon_sym_COLON,
    ACTIONS(104), 1,
      anon_sym_DOT,
    ACTIONS(108), 1,
      sym_comment,
    STATE(32), 1,
      aux_sym_identifier_path_repeat1,
    ACTIONS(106), 3,
      anon_sym_ATsource,
      aux_sym_entry_description_token1,
      anon_sym_LF,
  [584] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_LF,
    ACTIONS(73), 1,
      anon_sym_DASH,
    STATE(2), 1,
      aux_sym__blank_lines,
    STATE(14), 1,
      aux_sym_invariants_block_repeat1,
    STATE(63), 1,
      sym_prose_entry,
  [603] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      anon_sym_Scenario,
    ACTIONS(110), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(30), 2,
      sym_scenario_block,
      aux_sym_feature_repeat2,
  [618] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      anon_sym_Scenario,
    ACTIONS(36), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(30), 2,
      sym_scenario_block,
      aux_sym_feature_repeat2,
  [633] = 6,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_ATsource,
    ACTIONS(114), 1,
      aux_sym_entry_description_token1,
    ACTIONS(116), 1,
      anon_sym_LF,
    STATE(57), 1,
      sym_source_anchor,
    STATE(88), 1,
      sym_entry_description,
  [652] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      anon_sym_Scenario,
    ACTIONS(118), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(30), 2,
      sym_scenario_block,
      aux_sym_feature_repeat2,
  [667] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_Scenario,
    ACTIONS(120), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(30), 2,
      sym_scenario_block,
      aux_sym_feature_repeat2,
  [682] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      anon_sym_Scenario,
    ACTIONS(38), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(30), 2,
      sym_scenario_block,
      aux_sym_feature_repeat2,
  [697] = 4,
    ACTIONS(104), 1,
      anon_sym_DOT,
    ACTIONS(108), 1,
      sym_comment,
    STATE(33), 1,
      aux_sym_identifier_path_repeat1,
    ACTIONS(125), 3,
      anon_sym_ATsource,
      aux_sym_entry_description_token1,
      anon_sym_LF,
  [712] = 4,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_DOT,
    STATE(33), 1,
      aux_sym_identifier_path_repeat1,
    ACTIONS(130), 3,
      anon_sym_ATsource,
      aux_sym_entry_description_token1,
      anon_sym_LF,
  [727] = 4,
    ACTIONS(104), 1,
      anon_sym_DOT,
    ACTIONS(108), 1,
      sym_comment,
    STATE(32), 1,
      aux_sym_identifier_path_repeat1,
    ACTIONS(106), 3,
      anon_sym_ATsource,
      aux_sym_entry_description_token1,
      anon_sym_LF,
  [742] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_DASH,
    ACTIONS(69), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    STATE(17), 1,
      aux_sym_provides_block_repeat1,
    STATE(78), 1,
      sym_handle_entry,
  [761] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(54), 1,
      sym_identifier_path,
    STATE(28), 3,
      sym__handle,
      sym_prefixed_handle,
      sym_path_handle,
  [776] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_DASH,
    ACTIONS(69), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    STATE(11), 1,
      aux_sym_provides_block_repeat1,
    STATE(78), 1,
      sym_handle_entry,
  [795] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_LF,
    ACTIONS(73), 1,
      anon_sym_DASH,
    STATE(2), 1,
      aux_sym__blank_lines,
    STATE(13), 1,
      aux_sym_invariants_block_repeat1,
    STATE(63), 1,
      sym_prose_entry,
  [814] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    ACTIONS(134), 2,
      sym_frontmatter_key,
      anon_sym_Feature_COLON,
  [828] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      anon_sym_Feature_COLON,
    ACTIONS(136), 1,
      sym_frontmatter_key,
    STATE(40), 1,
      aux_sym_frontmatter_repeat1,
    STATE(75), 1,
      sym_frontmatter_entry,
  [844] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_frontmatter_key,
    ACTIONS(139), 1,
      anon_sym_Feature_COLON,
    STATE(40), 1,
      aux_sym_frontmatter_repeat1,
    STATE(75), 1,
      sym_frontmatter_entry,
  [860] = 2,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(130), 4,
      anon_sym_DOT,
      anon_sym_ATsource,
      aux_sym_entry_description_token1,
      anon_sym_LF,
  [870] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      ts_builtin_sym_end,
    ACTIONS(143), 1,
      anon_sym_LF,
    STATE(45), 1,
      aux_sym__blank_lines,
  [883] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      anon_sym_COMMA,
    ACTIONS(148), 1,
      anon_sym_RBRACK,
    STATE(44), 1,
      aux_sym_list_repeat1,
  [896] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_LF,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      aux_sym__blank_lines,
  [909] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
    ACTIONS(154), 1,
      anon_sym_LF,
    STATE(51), 1,
      aux_sym__blank_lines,
  [922] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
    ACTIONS(158), 1,
      anon_sym_LF,
    STATE(3), 1,
      aux_sym__blank_lines,
  [935] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_LF,
    ACTIONS(161), 1,
      sym_quoted_string,
    STATE(2), 1,
      aux_sym__blank_lines,
  [948] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_LF,
    ACTIONS(163), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      aux_sym__blank_lines,
  [961] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      ts_builtin_sym_end,
    ACTIONS(167), 1,
      anon_sym_LF,
    STATE(55), 1,
      aux_sym__blank_lines,
  [974] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_LF,
    ACTIONS(169), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      aux_sym__blank_lines,
  [987] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_COMMA,
    ACTIONS(173), 1,
      anon_sym_RBRACK,
    STATE(56), 1,
      aux_sym_list_repeat1,
  [1000] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      ts_builtin_sym_end,
    ACTIONS(177), 1,
      anon_sym_LF,
    STATE(4), 1,
      aux_sym__blank_lines,
  [1013] = 2,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(180), 3,
      anon_sym_ATsource,
      aux_sym_entry_description_token1,
      anon_sym_LF,
  [1022] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_LF,
    ACTIONS(182), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      aux_sym__blank_lines,
  [1035] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_COMMA,
    ACTIONS(186), 1,
      anon_sym_RBRACK,
    STATE(44), 1,
      aux_sym_list_repeat1,
  [1048] = 4,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(114), 1,
      aux_sym_entry_description_token1,
    ACTIONS(188), 1,
      anon_sym_LF,
    STATE(99), 1,
      sym_entry_description,
  [1061] = 2,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(190), 3,
      anon_sym_ATsource,
      aux_sym_entry_description_token1,
      anon_sym_LF,
  [1070] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      sym_quoted_string,
    ACTIONS(194), 1,
      anon_sym_LF,
    STATE(48), 1,
      aux_sym__blank_lines,
  [1083] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      ts_builtin_sym_end,
    ACTIONS(198), 1,
      anon_sym_LF,
    STATE(49), 1,
      aux_sym__blank_lines,
  [1096] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      sym_identifier,
    ACTIONS(202), 1,
      anon_sym_RBRACK,
  [1106] = 3,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(204), 1,
      aux_sym_entry_description_token1,
    STATE(96), 1,
      sym_prose_text,
  [1116] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_LF,
    STATE(21), 1,
      aux_sym__blank_lines,
  [1126] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_LF,
    STATE(12), 1,
      aux_sym__blank_lines,
  [1136] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      sym_identifier,
    ACTIONS(212), 1,
      anon_sym_RBRACK,
  [1146] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_Feature_COLON,
    STATE(50), 1,
      sym_feature,
  [1156] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_RBRACK,
    ACTIONS(200), 1,
      sym_identifier,
  [1166] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_LF,
    STATE(37), 1,
      aux_sym__blank_lines,
  [1176] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_LF,
    STATE(35), 1,
      aux_sym__blank_lines,
  [1186] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      anon_sym_LF,
    STATE(20), 1,
      aux_sym__blank_lines,
  [1196] = 3,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(220), 1,
      aux_sym_entry_description_token1,
    STATE(102), 1,
      sym_step_text,
  [1206] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_LF,
    STATE(38), 1,
      aux_sym__blank_lines,
  [1216] = 3,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(224), 1,
      aux_sym_entry_description_token1,
    STATE(80), 1,
      sym_scenario_name,
  [1226] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_LF,
    STATE(25), 1,
      aux_sym__blank_lines,
  [1236] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_LF,
    STATE(39), 1,
      aux_sym__blank_lines,
  [1246] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_COLON,
    ACTIONS(232), 1,
      anon_sym_LPAREN,
  [1256] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_Feature_COLON,
    STATE(60), 1,
      sym_feature,
  [1266] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_LF,
    STATE(19), 1,
      aux_sym__blank_lines,
  [1276] = 3,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(224), 1,
      aux_sym_entry_description_token1,
    STATE(64), 1,
      sym_scenario_name,
  [1286] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_LF,
    STATE(18), 1,
      aux_sym__blank_lines,
  [1296] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1304] = 2,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(238), 2,
      aux_sym_entry_description_token1,
      anon_sym_LF,
  [1312] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      sym_identifier,
    STATE(58), 1,
      sym_identifier_path,
  [1322] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      anon_sym_LF,
  [1329] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_LPAREN,
  [1336] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      anon_sym_LF,
  [1343] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      sym_identifier,
  [1350] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_LF,
  [1357] = 2,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(250), 1,
      aux_sym_entry_description_token1,
  [1364] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      ts_builtin_sym_end,
  [1371] = 2,
    ACTIONS(108), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_feature_name,
  [1378] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_LF,
  [1385] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_LF,
  [1392] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_COLON,
  [1399] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_LF,
  [1406] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      anon_sym_LF,
  [1413] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_LF,
  [1420] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      sym_quoted_string,
  [1427] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_LF,
  [1434] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_LF,
  [1441] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      anon_sym_LF,
  [1448] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_LF,
  [1455] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_RPAREN,
  [1462] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_COLON,
  [1469] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      anon_sym_RPAREN,
  [1476] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      sym_scenario_kind,
  [1483] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      sym_identifier,
  [1490] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 27,
  [SMALL_STATE(4)] = 67,
  [SMALL_STATE(5)] = 107,
  [SMALL_STATE(6)] = 142,
  [SMALL_STATE(7)] = 177,
  [SMALL_STATE(8)] = 206,
  [SMALL_STATE(9)] = 231,
  [SMALL_STATE(10)] = 256,
  [SMALL_STATE(11)] = 281,
  [SMALL_STATE(12)] = 303,
  [SMALL_STATE(13)] = 329,
  [SMALL_STATE(14)] = 351,
  [SMALL_STATE(15)] = 373,
  [SMALL_STATE(16)] = 395,
  [SMALL_STATE(17)] = 417,
  [SMALL_STATE(18)] = 439,
  [SMALL_STATE(19)] = 465,
  [SMALL_STATE(20)] = 484,
  [SMALL_STATE(21)] = 503,
  [SMALL_STATE(22)] = 522,
  [SMALL_STATE(23)] = 550,
  [SMALL_STATE(24)] = 566,
  [SMALL_STATE(25)] = 584,
  [SMALL_STATE(26)] = 603,
  [SMALL_STATE(27)] = 618,
  [SMALL_STATE(28)] = 633,
  [SMALL_STATE(29)] = 652,
  [SMALL_STATE(30)] = 667,
  [SMALL_STATE(31)] = 682,
  [SMALL_STATE(32)] = 697,
  [SMALL_STATE(33)] = 712,
  [SMALL_STATE(34)] = 727,
  [SMALL_STATE(35)] = 742,
  [SMALL_STATE(36)] = 761,
  [SMALL_STATE(37)] = 776,
  [SMALL_STATE(38)] = 795,
  [SMALL_STATE(39)] = 814,
  [SMALL_STATE(40)] = 828,
  [SMALL_STATE(41)] = 844,
  [SMALL_STATE(42)] = 860,
  [SMALL_STATE(43)] = 870,
  [SMALL_STATE(44)] = 883,
  [SMALL_STATE(45)] = 896,
  [SMALL_STATE(46)] = 909,
  [SMALL_STATE(47)] = 922,
  [SMALL_STATE(48)] = 935,
  [SMALL_STATE(49)] = 948,
  [SMALL_STATE(50)] = 961,
  [SMALL_STATE(51)] = 974,
  [SMALL_STATE(52)] = 987,
  [SMALL_STATE(53)] = 1000,
  [SMALL_STATE(54)] = 1013,
  [SMALL_STATE(55)] = 1022,
  [SMALL_STATE(56)] = 1035,
  [SMALL_STATE(57)] = 1048,
  [SMALL_STATE(58)] = 1061,
  [SMALL_STATE(59)] = 1070,
  [SMALL_STATE(60)] = 1083,
  [SMALL_STATE(61)] = 1096,
  [SMALL_STATE(62)] = 1106,
  [SMALL_STATE(63)] = 1116,
  [SMALL_STATE(64)] = 1126,
  [SMALL_STATE(65)] = 1136,
  [SMALL_STATE(66)] = 1146,
  [SMALL_STATE(67)] = 1156,
  [SMALL_STATE(68)] = 1166,
  [SMALL_STATE(69)] = 1176,
  [SMALL_STATE(70)] = 1186,
  [SMALL_STATE(71)] = 1196,
  [SMALL_STATE(72)] = 1206,
  [SMALL_STATE(73)] = 1216,
  [SMALL_STATE(74)] = 1226,
  [SMALL_STATE(75)] = 1236,
  [SMALL_STATE(76)] = 1246,
  [SMALL_STATE(77)] = 1256,
  [SMALL_STATE(78)] = 1266,
  [SMALL_STATE(79)] = 1276,
  [SMALL_STATE(80)] = 1286,
  [SMALL_STATE(81)] = 1296,
  [SMALL_STATE(82)] = 1304,
  [SMALL_STATE(83)] = 1312,
  [SMALL_STATE(84)] = 1322,
  [SMALL_STATE(85)] = 1329,
  [SMALL_STATE(86)] = 1336,
  [SMALL_STATE(87)] = 1343,
  [SMALL_STATE(88)] = 1350,
  [SMALL_STATE(89)] = 1357,
  [SMALL_STATE(90)] = 1364,
  [SMALL_STATE(91)] = 1371,
  [SMALL_STATE(92)] = 1378,
  [SMALL_STATE(93)] = 1385,
  [SMALL_STATE(94)] = 1392,
  [SMALL_STATE(95)] = 1399,
  [SMALL_STATE(96)] = 1406,
  [SMALL_STATE(97)] = 1413,
  [SMALL_STATE(98)] = 1420,
  [SMALL_STATE(99)] = 1427,
  [SMALL_STATE(100)] = 1434,
  [SMALL_STATE(101)] = 1441,
  [SMALL_STATE(102)] = 1448,
  [SMALL_STATE(103)] = 1455,
  [SMALL_STATE(104)] = 1462,
  [SMALL_STATE(105)] = 1469,
  [SMALL_STATE(106)] = 1476,
  [SMALL_STATE(107)] = 1483,
  [SMALL_STATE(108)] = 1490,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__blank_lines, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__blank_lines, 2, 0, 0), SHIFT_REPEAT(2),
  [16] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 4, 0, 5),
  [18] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [20] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [22] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_feature, 4, 0, 5), SHIFT(2),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 5, 0, 7),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_feature, 5, 0, 7), SHIFT(2),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 5, 0, 5),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 6, 0, 7),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_block, 5, 0, 12),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_block, 8, 0, 17),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scenario_block_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scenario_block_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_provides_block, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_invariants_block, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_out_of_scope_block, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_invariants_block_repeat1, 2, 0, 0),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_invariants_block_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_provides_block_repeat1, 2, 0, 0),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_provides_block_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_consumes_block, 3, 0, 0),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_provides_block_repeat1, 2, 0, 0), SHIFT(2),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scenario_block_repeat1, 2, 0, 0), SHIFT(2),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_invariants_block_repeat1, 2, 0, 0), SHIFT(2),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier_path, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 7, 0, 7),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_handle_entry, 2, 0, 8),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 6, 0, 5),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_feature_repeat2, 2, 0, 0),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_repeat2, 2, 0, 0), SHIFT_REPEAT(76),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier_path, 2, 0, 0),
  [127] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_identifier_path_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_identifier_path_repeat1, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_frontmatter_repeat1, 2, 0, 0),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_frontmatter_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 1),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 1),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 3),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 3, 0, 5),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_feature, 3, 0, 5), SHIFT(3),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 2),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 6),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 3),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 4, 0, 7),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_feature, 4, 0, 7), SHIFT(4),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_path_handle, 1, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 6),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_handle_entry, 3, 0, 10),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefixed_handle, 3, 0, 13),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 2),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [238] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_source_anchor, 4, 0, 16),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry_description, 1, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_handle_entry, 3, 0, 11),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_step_keyword, 1, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter_entry, 3, 0, 4),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_name, 1, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prose_text, 1, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prose_entry, 2, 0, 9),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_handle_entry, 4, 0, 14),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step_text, 1, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step, 2, 0, 15),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_trellis(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "trellis",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
