/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 103
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 62
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 13
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 15
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_COLON = 2,
  sym_frontmatter_key = 3,
  anon_sym_Feature_COLON = 4,
  sym_feature_name = 5,
  anon_sym_Provides_COLON = 6,
  anon_sym_Consumes_COLON = 7,
  anon_sym_Invariants_COLON = 8,
  anon_sym_OutOfScope_COLON = 9,
  anon_sym_DASH = 10,
  anon_sym_DOT = 11,
  aux_sym_entry_description_token1 = 12,
  anon_sym_Scenario = 13,
  anon_sym_LPAREN = 14,
  anon_sym_RPAREN = 15,
  sym_scenario_kind = 16,
  anon_sym_Given = 17,
  anon_sym_When = 18,
  anon_sym_Then = 19,
  anon_sym_And = 20,
  anon_sym_But = 21,
  sym_iso_date = 22,
  sym_quoted_string = 23,
  anon_sym_LBRACK = 24,
  anon_sym_COMMA = 25,
  anon_sym_RBRACK = 26,
  sym_comment = 27,
  anon_sym_LF = 28,
  sym_source_file = 29,
  sym_frontmatter = 30,
  sym_frontmatter_entry = 31,
  sym__frontmatter_value = 32,
  sym_feature = 33,
  sym__context_block = 34,
  sym_provides_block = 35,
  sym_consumes_block = 36,
  sym_invariants_block = 37,
  sym_out_of_scope_block = 38,
  sym_handle_entry = 39,
  sym__handle = 40,
  sym_prefixed_handle = 41,
  sym_path_handle = 42,
  sym_identifier_path = 43,
  sym_entry_description = 44,
  sym_prose_entry = 45,
  sym_prose_text = 46,
  sym_scenario_block = 47,
  sym_scenario_name = 48,
  sym_step = 49,
  sym_step_keyword = 50,
  sym_step_text = 51,
  sym_list = 52,
  aux_sym__blank_lines = 53,
  aux_sym_frontmatter_repeat1 = 54,
  aux_sym_feature_repeat1 = 55,
  aux_sym_feature_repeat2 = 56,
  aux_sym_provides_block_repeat1 = 57,
  aux_sym_invariants_block_repeat1 = 58,
  aux_sym_identifier_path_repeat1 = 59,
  aux_sym_scenario_block_repeat1 = 60,
  aux_sym_list_repeat1 = 61,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_COLON] = ":",
  [sym_frontmatter_key] = "frontmatter_key",
  [anon_sym_Feature_COLON] = "Feature:",
  [sym_feature_name] = "feature_name",
  [anon_sym_Provides_COLON] = "Provides:",
  [anon_sym_Consumes_COLON] = "Consumes:",
  [anon_sym_Invariants_COLON] = "Invariants:",
  [anon_sym_OutOfScope_COLON] = "OutOfScope:",
  [anon_sym_DASH] = "-",
  [anon_sym_DOT] = ".",
  [aux_sym_entry_description_token1] = "entry_description_token1",
  [anon_sym_Scenario] = "Scenario",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_scenario_kind] = "scenario_kind",
  [anon_sym_Given] = "Given",
  [anon_sym_When] = "When",
  [anon_sym_Then] = "Then",
  [anon_sym_And] = "And",
  [anon_sym_But] = "But",
  [sym_iso_date] = "iso_date",
  [sym_quoted_string] = "quoted_string",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [sym_comment] = "comment",
  [anon_sym_LF] = "\n",
  [sym_source_file] = "source_file",
  [sym_frontmatter] = "frontmatter",
  [sym_frontmatter_entry] = "frontmatter_entry",
  [sym__frontmatter_value] = "_frontmatter_value",
  [sym_feature] = "feature",
  [sym__context_block] = "_context_block",
  [sym_provides_block] = "provides_block",
  [sym_consumes_block] = "consumes_block",
  [sym_invariants_block] = "invariants_block",
  [sym_out_of_scope_block] = "out_of_scope_block",
  [sym_handle_entry] = "handle_entry",
  [sym__handle] = "_handle",
  [sym_prefixed_handle] = "prefixed_handle",
  [sym_path_handle] = "path_handle",
  [sym_identifier_path] = "identifier_path",
  [sym_entry_description] = "entry_description",
  [sym_prose_entry] = "prose_entry",
  [sym_prose_text] = "prose_text",
  [sym_scenario_block] = "scenario_block",
  [sym_scenario_name] = "scenario_name",
  [sym_step] = "step",
  [sym_step_keyword] = "step_keyword",
  [sym_step_text] = "step_text",
  [sym_list] = "list",
  [aux_sym__blank_lines] = "_blank_lines",
  [aux_sym_frontmatter_repeat1] = "frontmatter_repeat1",
  [aux_sym_feature_repeat1] = "feature_repeat1",
  [aux_sym_feature_repeat2] = "feature_repeat2",
  [aux_sym_provides_block_repeat1] = "provides_block_repeat1",
  [aux_sym_invariants_block_repeat1] = "invariants_block_repeat1",
  [aux_sym_identifier_path_repeat1] = "identifier_path_repeat1",
  [aux_sym_scenario_block_repeat1] = "scenario_block_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_frontmatter_key] = sym_frontmatter_key,
  [anon_sym_Feature_COLON] = anon_sym_Feature_COLON,
  [sym_feature_name] = sym_feature_name,
  [anon_sym_Provides_COLON] = anon_sym_Provides_COLON,
  [anon_sym_Consumes_COLON] = anon_sym_Consumes_COLON,
  [anon_sym_Invariants_COLON] = anon_sym_Invariants_COLON,
  [anon_sym_OutOfScope_COLON] = anon_sym_OutOfScope_COLON,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [aux_sym_entry_description_token1] = aux_sym_entry_description_token1,
  [anon_sym_Scenario] = anon_sym_Scenario,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_scenario_kind] = sym_scenario_kind,
  [anon_sym_Given] = anon_sym_Given,
  [anon_sym_When] = anon_sym_When,
  [anon_sym_Then] = anon_sym_Then,
  [anon_sym_And] = anon_sym_And,
  [anon_sym_But] = anon_sym_But,
  [sym_iso_date] = sym_iso_date,
  [sym_quoted_string] = sym_quoted_string,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_comment] = sym_comment,
  [anon_sym_LF] = anon_sym_LF,
  [sym_source_file] = sym_source_file,
  [sym_frontmatter] = sym_frontmatter,
  [sym_frontmatter_entry] = sym_frontmatter_entry,
  [sym__frontmatter_value] = sym__frontmatter_value,
  [sym_feature] = sym_feature,
  [sym__context_block] = sym__context_block,
  [sym_provides_block] = sym_provides_block,
  [sym_consumes_block] = sym_consumes_block,
  [sym_invariants_block] = sym_invariants_block,
  [sym_out_of_scope_block] = sym_out_of_scope_block,
  [sym_handle_entry] = sym_handle_entry,
  [sym__handle] = sym__handle,
  [sym_prefixed_handle] = sym_prefixed_handle,
  [sym_path_handle] = sym_path_handle,
  [sym_identifier_path] = sym_identifier_path,
  [sym_entry_description] = sym_entry_description,
  [sym_prose_entry] = sym_prose_entry,
  [sym_prose_text] = sym_prose_text,
  [sym_scenario_block] = sym_scenario_block,
  [sym_scenario_name] = sym_scenario_name,
  [sym_step] = sym_step,
  [sym_step_keyword] = sym_step_keyword,
  [sym_step_text] = sym_step_text,
  [sym_list] = sym_list,
  [aux_sym__blank_lines] = aux_sym__blank_lines,
  [aux_sym_frontmatter_repeat1] = aux_sym_frontmatter_repeat1,
  [aux_sym_feature_repeat1] = aux_sym_feature_repeat1,
  [aux_sym_feature_repeat2] = aux_sym_feature_repeat2,
  [aux_sym_provides_block_repeat1] = aux_sym_provides_block_repeat1,
  [aux_sym_invariants_block_repeat1] = aux_sym_invariants_block_repeat1,
  [aux_sym_identifier_path_repeat1] = aux_sym_identifier_path_repeat1,
  [aux_sym_scenario_block_repeat1] = aux_sym_scenario_block_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_frontmatter_key] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Feature_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_feature_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Provides_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Consumes_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Invariants_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OutOfScope_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_entry_description_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_Scenario] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_scenario_kind] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Given] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_When] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_And] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_But] = {
    .visible = true,
    .named = false,
  },
  [sym_iso_date] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_frontmatter] = {
    .visible = true,
    .named = true,
  },
  [sym_frontmatter_entry] = {
    .visible = true,
    .named = true,
  },
  [sym__frontmatter_value] = {
    .visible = false,
    .named = true,
  },
  [sym_feature] = {
    .visible = true,
    .named = true,
  },
  [sym__context_block] = {
    .visible = false,
    .named = true,
  },
  [sym_provides_block] = {
    .visible = true,
    .named = true,
  },
  [sym_consumes_block] = {
    .visible = true,
    .named = true,
  },
  [sym_invariants_block] = {
    .visible = true,
    .named = true,
  },
  [sym_out_of_scope_block] = {
    .visible = true,
    .named = true,
  },
  [sym_handle_entry] = {
    .visible = true,
    .named = true,
  },
  [sym__handle] = {
    .visible = false,
    .named = true,
  },
  [sym_prefixed_handle] = {
    .visible = true,
    .named = true,
  },
  [sym_path_handle] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier_path] = {
    .visible = true,
    .named = true,
  },
  [sym_entry_description] = {
    .visible = true,
    .named = true,
  },
  [sym_prose_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_prose_text] = {
    .visible = true,
    .named = true,
  },
  [sym_scenario_block] = {
    .visible = true,
    .named = true,
  },
  [sym_scenario_name] = {
    .visible = true,
    .named = true,
  },
  [sym_step] = {
    .visible = true,
    .named = true,
  },
  [sym_step_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_step_text] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__blank_lines] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_frontmatter_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_feature_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_feature_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_provides_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_invariants_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_path_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scenario_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_description = 1,
  field_feature = 2,
  field_frontmatter = 3,
  field_handle = 4,
  field_key = 5,
  field_keyword = 6,
  field_kind = 7,
  field_name = 8,
  field_path = 9,
  field_prefix = 10,
  field_summary = 11,
  field_text = 12,
  field_value = 13,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_description] = "description",
  [field_feature] = "feature",
  [field_frontmatter] = "frontmatter",
  [field_handle] = "handle",
  [field_key] = "key",
  [field_keyword] = "keyword",
  [field_kind] = "kind",
  [field_name] = "name",
  [field_path] = "path",
  [field_prefix] = "prefix",
  [field_summary] = "summary",
  [field_text] = "text",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 2},
  [8] = {.index = 12, .length = 1},
  [9] = {.index = 13, .length = 1},
  [10] = {.index = 14, .length = 2},
  [11] = {.index = 16, .length = 1},
  [12] = {.index = 17, .length = 2},
  [13] = {.index = 19, .length = 2},
  [14] = {.index = 21, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_feature, 0},
  [1] =
    {field_feature, 1},
    {field_frontmatter, 0},
  [3] =
    {field_feature, 1},
  [4] =
    {field_key, 0},
    {field_value, 2},
  [6] =
    {field_name, 1},
    {field_summary, 2},
  [8] =
    {field_feature, 2},
    {field_frontmatter, 1},
  [10] =
    {field_name, 1},
    {field_summary, 3},
  [12] =
    {field_handle, 1},
  [13] =
    {field_text, 1},
  [14] =
    {field_description, 2},
    {field_handle, 1},
  [16] =
    {field_name, 2},
  [17] =
    {field_path, 2},
    {field_prefix, 0},
  [19] =
    {field_keyword, 0},
    {field_text, 1},
  [21] =
    {field_kind, 2},
    {field_name, 5},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(27);
      ADVANCE_MAP(
        '\n', 97,
        '"', 5,
        '#', 96,
        '(', 45,
        ')', 46,
        ',', 94,
        '-', 38,
        '.', 39,
        ':', 28,
        '@', 24,
        'C', 72,
        'F', 59,
        'I', 68,
        'O', 85,
        'P', 75,
        '[', 93,
        ']', 95,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '#') ADVANCE(96);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == ':') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(40);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '#') ADVANCE(96);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '#') ADVANCE(96);
      if (lookahead == '@') ADVANCE(24);
      if (lookahead == 'F') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '#') ADVANCE(96);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(96);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(33);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(30);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 16:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(91);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 24:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 25:
      if (eof) ADVANCE(27);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '#') ADVANCE(96);
      if (lookahead == '[') ADVANCE(93);
      if (lookahead == ']') ADVANCE(95);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 26:
      if (eof) ADVANCE(27);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '#') ADVANCE(96);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == 'C') ADVANCE(72);
      if (lookahead == 'I') ADVANCE(68);
      if (lookahead == 'O') ADVANCE(85);
      if (lookahead == 'P') ADVANCE(75);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_frontmatter_key);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_Feature_COLON);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_feature_name);
      if (lookahead == '"') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_feature_name);
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_feature_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_Provides_COLON);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_Consumes_COLON);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_Invariants_COLON);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_OutOfScope_COLON);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_entry_description_token1);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '#') ADVANCE(96);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == ':') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(40);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_entry_description_token1);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '#') ADVANCE(96);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_entry_description_token1);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '#') ADVANCE(96);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_entry_description_token1);
      if (lookahead == '#') ADVANCE(96);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_entry_description_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(30);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(35);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(34);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(36);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(37);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O') ADVANCE(64);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S') ADVANCE(57);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(76);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(83);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(71);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(63);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(55);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(47);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(79);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(51);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(80);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(53);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(58);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(56);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(61);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(89);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(78);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(84);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(74);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(69);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(62);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(73);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(66);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(60);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(86);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(48);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(49);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(50);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(52);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(81);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(82);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(67);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(77);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'v') ADVANCE(65);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'v') ADVANCE(54);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_iso_date);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_quoted_string);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'A') ADVANCE(1);
      if (lookahead == 'B') ADVANCE(2);
      if (lookahead == 'G') ADVANCE(3);
      if (lookahead == 'S') ADVANCE(4);
      if (lookahead == 'T') ADVANCE(5);
      if (lookahead == 'W') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'i') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'c') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'h') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'h') ADVANCE(13);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_scenario_kind);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 10:
      if (lookahead == 'v') ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_And);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_But);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_Then);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_When);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_Given);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_Scenario);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 3},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 26},
  [4] = {.lex_state = 26},
  [5] = {.lex_state = 26},
  [6] = {.lex_state = 26},
  [7] = {.lex_state = 26},
  [8] = {.lex_state = 25},
  [9] = {.lex_state = 25},
  [10] = {.lex_state = 25},
  [11] = {.lex_state = 26},
  [12] = {.lex_state = 26},
  [13] = {.lex_state = 26},
  [14] = {.lex_state = 26},
  [15] = {.lex_state = 26},
  [16] = {.lex_state = 25},
  [17] = {.lex_state = 26},
  [18] = {.lex_state = 25},
  [19] = {.lex_state = 26},
  [20] = {.lex_state = 26},
  [21] = {.lex_state = 25},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 25},
  [24] = {.lex_state = 25},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 25},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 25},
  [30] = {.lex_state = 25},
  [31] = {.lex_state = 25},
  [32] = {.lex_state = 25},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 6},
  [62] = {.lex_state = 6},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 4},
  [66] = {.lex_state = 25},
  [67] = {.lex_state = 25},
  [68] = {.lex_state = 25},
  [69] = {.lex_state = 25},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 6},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 6},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 4},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 3},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 3},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 25},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 6},
  [88] = {.lex_state = 7},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 25},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 25},
  [102] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_frontmatter_key] = ACTIONS(1),
    [anon_sym_Feature_COLON] = ACTIONS(1),
    [anon_sym_Provides_COLON] = ACTIONS(1),
    [anon_sym_Consumes_COLON] = ACTIONS(1),
    [anon_sym_Invariants_COLON] = ACTIONS(1),
    [anon_sym_OutOfScope_COLON] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_Scenario] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_scenario_kind] = ACTIONS(1),
    [anon_sym_Given] = ACTIONS(1),
    [anon_sym_When] = ACTIONS(1),
    [anon_sym_Then] = ACTIONS(1),
    [anon_sym_And] = ACTIONS(1),
    [anon_sym_But] = ACTIONS(1),
    [sym_iso_date] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(84),
    [sym_frontmatter] = STATE(79),
    [sym_frontmatter_entry] = STATE(60),
    [sym_feature] = STATE(41),
    [aux_sym__blank_lines] = STATE(22),
    [aux_sym_frontmatter_repeat1] = STATE(36),
    [sym_frontmatter_key] = ACTIONS(5),
    [anon_sym_Feature_COLON] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    ACTIONS(11), 15,
      ts_builtin_sym_end,
      sym_frontmatter_key,
      anon_sym_Feature_COLON,
      anon_sym_Provides_COLON,
      anon_sym_Consumes_COLON,
      anon_sym_Invariants_COLON,
      anon_sym_OutOfScope_COLON,
      anon_sym_DASH,
      anon_sym_Scenario,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
      sym_quoted_string,
  [27] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(16), 1,
      ts_builtin_sym_end,
    ACTIONS(18), 1,
      anon_sym_Provides_COLON,
    ACTIONS(20), 1,
      anon_sym_Consumes_COLON,
    ACTIONS(22), 1,
      anon_sym_Invariants_COLON,
    ACTIONS(24), 1,
      anon_sym_OutOfScope_COLON,
    ACTIONS(26), 1,
      anon_sym_Scenario,
    ACTIONS(28), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    STATE(32), 2,
      sym_scenario_block,
      aux_sym_feature_repeat2,
    STATE(5), 6,
      sym__context_block,
      sym_provides_block,
      sym_consumes_block,
      sym_invariants_block,
      sym_out_of_scope_block,
      aux_sym_feature_repeat1,
  [67] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(18), 1,
      anon_sym_Provides_COLON,
    ACTIONS(20), 1,
      anon_sym_Consumes_COLON,
    ACTIONS(22), 1,
      anon_sym_Invariants_COLON,
    ACTIONS(24), 1,
      anon_sym_OutOfScope_COLON,
    ACTIONS(26), 1,
      anon_sym_Scenario,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(33), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    STATE(24), 2,
      sym_scenario_block,
      aux_sym_feature_repeat2,
    STATE(6), 6,
      sym__context_block,
      sym_provides_block,
      sym_consumes_block,
      sym_invariants_block,
      sym_out_of_scope_block,
      aux_sym_feature_repeat1,
  [107] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(18), 1,
      anon_sym_Provides_COLON,
    ACTIONS(20), 1,
      anon_sym_Consumes_COLON,
    ACTIONS(22), 1,
      anon_sym_Invariants_COLON,
    ACTIONS(24), 1,
      anon_sym_OutOfScope_COLON,
    ACTIONS(26), 1,
      anon_sym_Scenario,
    ACTIONS(36), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(30), 2,
      sym_scenario_block,
      aux_sym_feature_repeat2,
    STATE(7), 6,
      sym__context_block,
      sym_provides_block,
      sym_consumes_block,
      sym_invariants_block,
      sym_out_of_scope_block,
      aux_sym_feature_repeat1,
  [142] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(18), 1,
      anon_sym_Provides_COLON,
    ACTIONS(20), 1,
      anon_sym_Consumes_COLON,
    ACTIONS(22), 1,
      anon_sym_Invariants_COLON,
    ACTIONS(24), 1,
      anon_sym_OutOfScope_COLON,
    ACTIONS(26), 1,
      anon_sym_Scenario,
    ACTIONS(38), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(26), 2,
      sym_scenario_block,
      aux_sym_feature_repeat2,
    STATE(7), 6,
      sym__context_block,
      sym_provides_block,
      sym_consumes_block,
      sym_invariants_block,
      sym_out_of_scope_block,
      aux_sym_feature_repeat1,
  [177] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      anon_sym_Provides_COLON,
    ACTIONS(45), 1,
      anon_sym_Consumes_COLON,
    ACTIONS(48), 1,
      anon_sym_Invariants_COLON,
    ACTIONS(51), 1,
      anon_sym_OutOfScope_COLON,
    ACTIONS(40), 3,
      ts_builtin_sym_end,
      anon_sym_Scenario,
      anon_sym_LF,
    STATE(7), 6,
      sym__context_block,
      sym_provides_block,
      sym_consumes_block,
      sym_invariants_block,
      sym_out_of_scope_block,
      aux_sym_feature_repeat1,
  [206] = 6,
    ACTIONS(3), 1,
      sym_comment,
    STATE(9), 1,
      aux_sym_scenario_block_repeat1,
    STATE(71), 1,
      sym_step,
    STATE(72), 1,
      sym_step_keyword,
    ACTIONS(54), 3,
      ts_builtin_sym_end,
      anon_sym_Scenario,
      anon_sym_LF,
    ACTIONS(56), 5,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
  [231] = 6,
    ACTIONS(3), 1,
      sym_comment,
    STATE(9), 1,
      aux_sym_scenario_block_repeat1,
    STATE(71), 1,
      sym_step,
    STATE(72), 1,
      sym_step_keyword,
    ACTIONS(58), 3,
      ts_builtin_sym_end,
      anon_sym_Scenario,
      anon_sym_LF,
    ACTIONS(60), 5,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
  [256] = 6,
    ACTIONS(3), 1,
      sym_comment,
    STATE(9), 1,
      aux_sym_scenario_block_repeat1,
    STATE(71), 1,
      sym_step,
    STATE(72), 1,
      sym_step_keyword,
    ACTIONS(63), 3,
      ts_builtin_sym_end,
      anon_sym_Scenario,
      anon_sym_LF,
    ACTIONS(56), 5,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
  [281] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_DASH,
    STATE(15), 1,
      aux_sym_provides_block_repeat1,
    STATE(59), 1,
      sym_handle_entry,
    ACTIONS(65), 7,
      ts_builtin_sym_end,
      anon_sym_Provides_COLON,
      anon_sym_Consumes_COLON,
      anon_sym_Invariants_COLON,
      anon_sym_OutOfScope_COLON,
      anon_sym_Scenario,
      anon_sym_LF,
  [303] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_DASH,
    STATE(15), 1,
      aux_sym_provides_block_repeat1,
    STATE(59), 1,
      sym_handle_entry,
    ACTIONS(69), 7,
      ts_builtin_sym_end,
      anon_sym_Provides_COLON,
      anon_sym_Consumes_COLON,
      anon_sym_Invariants_COLON,
      anon_sym_OutOfScope_COLON,
      anon_sym_Scenario,
      anon_sym_LF,
  [325] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_DASH,
    STATE(14), 1,
      aux_sym_invariants_block_repeat1,
    STATE(63), 1,
      sym_prose_entry,
    ACTIONS(71), 7,
      ts_builtin_sym_end,
      anon_sym_Provides_COLON,
      anon_sym_Consumes_COLON,
      anon_sym_Invariants_COLON,
      anon_sym_OutOfScope_COLON,
      anon_sym_Scenario,
      anon_sym_LF,
  [347] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_DASH,
    STATE(14), 1,
      aux_sym_invariants_block_repeat1,
    STATE(63), 1,
      sym_prose_entry,
    ACTIONS(75), 7,
      ts_builtin_sym_end,
      anon_sym_Provides_COLON,
      anon_sym_Consumes_COLON,
      anon_sym_Invariants_COLON,
      anon_sym_OutOfScope_COLON,
      anon_sym_Scenario,
      anon_sym_LF,
  [369] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_DASH,
    STATE(15), 1,
      aux_sym_provides_block_repeat1,
    STATE(59), 1,
      sym_handle_entry,
    ACTIONS(80), 7,
      ts_builtin_sym_end,
      anon_sym_Provides_COLON,
      anon_sym_Consumes_COLON,
      anon_sym_Invariants_COLON,
      anon_sym_OutOfScope_COLON,
      anon_sym_Scenario,
      anon_sym_LF,
  [391] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    STATE(8), 1,
      aux_sym_scenario_block_repeat1,
    STATE(71), 1,
      sym_step,
    STATE(72), 1,
      sym_step_keyword,
    ACTIONS(56), 5,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
  [417] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_DASH,
    STATE(14), 1,
      aux_sym_invariants_block_repeat1,
    STATE(63), 1,
      sym_prose_entry,
    ACTIONS(87), 7,
      ts_builtin_sym_end,
      anon_sym_Provides_COLON,
      anon_sym_Consumes_COLON,
      anon_sym_Invariants_COLON,
      anon_sym_OutOfScope_COLON,
      anon_sym_Scenario,
      anon_sym_LF,
  [439] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    STATE(10), 1,
      aux_sym_scenario_block_repeat1,
    STATE(71), 1,
      sym_step,
    STATE(72), 1,
      sym_step_keyword,
    ACTIONS(56), 5,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
  [465] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    ACTIONS(80), 7,
      ts_builtin_sym_end,
      anon_sym_Provides_COLON,
      anon_sym_Consumes_COLON,
      anon_sym_Invariants_COLON,
      anon_sym_OutOfScope_COLON,
      anon_sym_DASH,
      anon_sym_Scenario,
  [484] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    ACTIONS(75), 7,
      ts_builtin_sym_end,
      anon_sym_Provides_COLON,
      anon_sym_Consumes_COLON,
      anon_sym_Invariants_COLON,
      anon_sym_OutOfScope_COLON,
      anon_sym_DASH,
      anon_sym_Scenario,
  [503] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    ACTIONS(58), 7,
      ts_builtin_sym_end,
      anon_sym_Scenario,
      anon_sym_Given,
      anon_sym_When,
      anon_sym_Then,
      anon_sym_And,
      anon_sym_But,
  [522] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_frontmatter_key,
    ACTIONS(7), 1,
      anon_sym_Feature_COLON,
    ACTIONS(85), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    STATE(36), 1,
      aux_sym_frontmatter_repeat1,
    STATE(45), 1,
      sym_feature,
    STATE(60), 1,
      sym_frontmatter_entry,
    STATE(81), 1,
      sym_frontmatter,
  [550] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_LBRACK,
    STATE(91), 2,
      sym__frontmatter_value,
      sym_list,
    ACTIONS(98), 3,
      sym_identifier,
      sym_iso_date,
      sym_quoted_string,
  [566] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      anon_sym_Scenario,
    ACTIONS(38), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(29), 2,
      sym_scenario_block,
      aux_sym_feature_repeat2,
  [581] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(85), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    STATE(13), 1,
      aux_sym_invariants_block_repeat1,
    STATE(63), 1,
      sym_prose_entry,
  [600] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      anon_sym_Scenario,
    ACTIONS(102), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(29), 2,
      sym_scenario_block,
      aux_sym_feature_repeat2,
  [615] = 5,
    ACTIONS(104), 1,
      anon_sym_COLON,
    ACTIONS(106), 1,
      anon_sym_DOT,
    ACTIONS(110), 1,
      sym_comment,
    STATE(38), 1,
      aux_sym_identifier_path_repeat1,
    ACTIONS(108), 2,
      aux_sym_entry_description_token1,
      anon_sym_LF,
  [632] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(85), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    STATE(17), 1,
      aux_sym_invariants_block_repeat1,
    STATE(63), 1,
      sym_prose_entry,
  [651] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_Scenario,
    ACTIONS(112), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(29), 2,
      sym_scenario_block,
      aux_sym_feature_repeat2,
  [666] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      anon_sym_Scenario,
    ACTIONS(117), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(29), 2,
      sym_scenario_block,
      aux_sym_feature_repeat2,
  [681] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      sym_identifier,
    STATE(65), 1,
      sym_identifier_path,
    STATE(52), 3,
      sym__handle,
      sym_prefixed_handle,
      sym_path_handle,
  [696] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      anon_sym_Scenario,
    ACTIONS(36), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(29), 2,
      sym_scenario_block,
      aux_sym_feature_repeat2,
  [711] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_DASH,
    ACTIONS(85), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    STATE(11), 1,
      aux_sym_provides_block_repeat1,
    STATE(59), 1,
      sym_handle_entry,
  [730] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_DASH,
    ACTIONS(85), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    STATE(12), 1,
      aux_sym_provides_block_repeat1,
    STATE(59), 1,
      sym_handle_entry,
  [749] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LF,
    STATE(2), 1,
      aux_sym__blank_lines,
    ACTIONS(121), 2,
      sym_frontmatter_key,
      anon_sym_Feature_COLON,
  [763] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_frontmatter_key,
    ACTIONS(123), 1,
      anon_sym_Feature_COLON,
    STATE(40), 1,
      aux_sym_frontmatter_repeat1,
    STATE(60), 1,
      sym_frontmatter_entry,
  [779] = 4,
    ACTIONS(106), 1,
      anon_sym_DOT,
    ACTIONS(110), 1,
      sym_comment,
    STATE(38), 1,
      aux_sym_identifier_path_repeat1,
    ACTIONS(108), 2,
      aux_sym_entry_description_token1,
      anon_sym_LF,
  [793] = 4,
    ACTIONS(106), 1,
      anon_sym_DOT,
    ACTIONS(110), 1,
      sym_comment,
    STATE(39), 1,
      aux_sym_identifier_path_repeat1,
    ACTIONS(125), 2,
      aux_sym_entry_description_token1,
      anon_sym_LF,
  [807] = 4,
    ACTIONS(110), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_DOT,
    STATE(39), 1,
      aux_sym_identifier_path_repeat1,
    ACTIONS(130), 2,
      aux_sym_entry_description_token1,
      anon_sym_LF,
  [821] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_Feature_COLON,
    ACTIONS(132), 1,
      sym_frontmatter_key,
    STATE(40), 1,
      aux_sym_frontmatter_repeat1,
    STATE(60), 1,
      sym_frontmatter_entry,
  [837] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      ts_builtin_sym_end,
    ACTIONS(137), 1,
      anon_sym_LF,
    STATE(44), 1,
      aux_sym__blank_lines,
  [850] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
    ACTIONS(141), 1,
      anon_sym_LF,
    STATE(48), 1,
      aux_sym__blank_lines,
  [863] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_COMMA,
    ACTIONS(146), 1,
      anon_sym_RBRACK,
    STATE(43), 1,
      aux_sym_list_repeat1,
  [876] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LF,
    ACTIONS(148), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      aux_sym__blank_lines,
  [889] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
    ACTIONS(152), 1,
      anon_sym_LF,
    STATE(50), 1,
      aux_sym__blank_lines,
  [902] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
    ACTIONS(156), 1,
      anon_sym_LF,
    STATE(3), 1,
      aux_sym__blank_lines,
  [915] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LF,
    ACTIONS(159), 1,
      sym_quoted_string,
    STATE(2), 1,
      aux_sym__blank_lines,
  [928] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LF,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      aux_sym__blank_lines,
  [941] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      ts_builtin_sym_end,
    ACTIONS(165), 1,
      anon_sym_LF,
    STATE(54), 1,
      aux_sym__blank_lines,
  [954] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LF,
    ACTIONS(167), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      aux_sym__blank_lines,
  [967] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_COMMA,
    ACTIONS(171), 1,
      anon_sym_RBRACK,
    STATE(55), 1,
      aux_sym_list_repeat1,
  [980] = 4,
    ACTIONS(110), 1,
      sym_comment,
    ACTIONS(173), 1,
      aux_sym_entry_description_token1,
    ACTIONS(175), 1,
      anon_sym_LF,
    STATE(86), 1,
      sym_entry_description,
  [993] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      ts_builtin_sym_end,
    ACTIONS(179), 1,
      anon_sym_LF,
    STATE(4), 1,
      aux_sym__blank_lines,
  [1006] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LF,
    ACTIONS(182), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      aux_sym__blank_lines,
  [1019] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_COMMA,
    ACTIONS(186), 1,
      anon_sym_RBRACK,
    STATE(43), 1,
      aux_sym_list_repeat1,
  [1032] = 2,
    ACTIONS(110), 1,
      sym_comment,
    ACTIONS(130), 3,
      anon_sym_DOT,
      aux_sym_entry_description_token1,
      anon_sym_LF,
  [1041] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      sym_quoted_string,
    ACTIONS(190), 1,
      anon_sym_LF,
    STATE(47), 1,
      aux_sym__blank_lines,
  [1054] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1062] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_LF,
    STATE(19), 1,
      aux_sym__blank_lines,
  [1072] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_LF,
    STATE(35), 1,
      aux_sym__blank_lines,
  [1082] = 3,
    ACTIONS(110), 1,
      sym_comment,
    ACTIONS(196), 1,
      aux_sym_entry_description_token1,
    STATE(64), 1,
      sym_scenario_name,
  [1092] = 3,
    ACTIONS(110), 1,
      sym_comment,
    ACTIONS(198), 1,
      aux_sym_entry_description_token1,
    STATE(93), 1,
      sym_prose_text,
  [1102] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_LF,
    STATE(20), 1,
      aux_sym__blank_lines,
  [1112] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_LF,
    STATE(16), 1,
      aux_sym__blank_lines,
  [1122] = 2,
    ACTIONS(110), 1,
      sym_comment,
    ACTIONS(204), 2,
      aux_sym_entry_description_token1,
      anon_sym_LF,
  [1130] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      sym_identifier,
    ACTIONS(208), 1,
      anon_sym_RBRACK,
  [1140] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_RBRACK,
    ACTIONS(210), 1,
      sym_identifier,
  [1150] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      sym_identifier,
    ACTIONS(212), 1,
      anon_sym_RBRACK,
  [1160] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      sym_identifier,
    STATE(76), 1,
      sym_identifier_path,
  [1170] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_LF,
    STATE(33), 1,
      aux_sym__blank_lines,
  [1180] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      anon_sym_LF,
    STATE(21), 1,
      aux_sym__blank_lines,
  [1190] = 3,
    ACTIONS(110), 1,
      sym_comment,
    ACTIONS(220), 1,
      aux_sym_entry_description_token1,
    STATE(98), 1,
      sym_step_text,
  [1200] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_LF,
    STATE(34), 1,
      aux_sym__blank_lines,
  [1210] = 3,
    ACTIONS(110), 1,
      sym_comment,
    ACTIONS(196), 1,
      aux_sym_entry_description_token1,
    STATE(80), 1,
      sym_scenario_name,
  [1220] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      anon_sym_LF,
    STATE(25), 1,
      aux_sym__blank_lines,
  [1230] = 2,
    ACTIONS(110), 1,
      sym_comment,
    ACTIONS(226), 2,
      aux_sym_entry_description_token1,
      anon_sym_LF,
  [1238] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_LF,
    STATE(28), 1,
      aux_sym__blank_lines,
  [1248] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_COLON,
    ACTIONS(232), 1,
      anon_sym_LPAREN,
  [1258] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_Feature_COLON,
    STATE(42), 1,
      sym_feature,
  [1268] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_LF,
    STATE(18), 1,
      aux_sym__blank_lines,
  [1278] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_Feature_COLON,
    STATE(49), 1,
      sym_feature,
  [1288] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_LF,
  [1295] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      sym_identifier,
  [1302] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      ts_builtin_sym_end,
  [1309] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      anon_sym_LF,
  [1316] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_LF,
  [1323] = 2,
    ACTIONS(110), 1,
      sym_comment,
    ACTIONS(246), 1,
      aux_sym_entry_description_token1,
  [1330] = 2,
    ACTIONS(110), 1,
      sym_comment,
    ACTIONS(248), 1,
      sym_feature_name,
  [1337] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_COLON,
  [1344] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_LF,
  [1351] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_LF,
  [1358] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_LF,
  [1365] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_LF,
  [1372] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_LF,
  [1379] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      sym_scenario_kind,
  [1386] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      anon_sym_LF,
  [1393] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_LF,
  [1400] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_LF,
  [1407] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
  [1414] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_COLON,
  [1421] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      sym_identifier,
  [1428] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 27,
  [SMALL_STATE(4)] = 67,
  [SMALL_STATE(5)] = 107,
  [SMALL_STATE(6)] = 142,
  [SMALL_STATE(7)] = 177,
  [SMALL_STATE(8)] = 206,
  [SMALL_STATE(9)] = 231,
  [SMALL_STATE(10)] = 256,
  [SMALL_STATE(11)] = 281,
  [SMALL_STATE(12)] = 303,
  [SMALL_STATE(13)] = 325,
  [SMALL_STATE(14)] = 347,
  [SMALL_STATE(15)] = 369,
  [SMALL_STATE(16)] = 391,
  [SMALL_STATE(17)] = 417,
  [SMALL_STATE(18)] = 439,
  [SMALL_STATE(19)] = 465,
  [SMALL_STATE(20)] = 484,
  [SMALL_STATE(21)] = 503,
  [SMALL_STATE(22)] = 522,
  [SMALL_STATE(23)] = 550,
  [SMALL_STATE(24)] = 566,
  [SMALL_STATE(25)] = 581,
  [SMALL_STATE(26)] = 600,
  [SMALL_STATE(27)] = 615,
  [SMALL_STATE(28)] = 632,
  [SMALL_STATE(29)] = 651,
  [SMALL_STATE(30)] = 666,
  [SMALL_STATE(31)] = 681,
  [SMALL_STATE(32)] = 696,
  [SMALL_STATE(33)] = 711,
  [SMALL_STATE(34)] = 730,
  [SMALL_STATE(35)] = 749,
  [SMALL_STATE(36)] = 763,
  [SMALL_STATE(37)] = 779,
  [SMALL_STATE(38)] = 793,
  [SMALL_STATE(39)] = 807,
  [SMALL_STATE(40)] = 821,
  [SMALL_STATE(41)] = 837,
  [SMALL_STATE(42)] = 850,
  [SMALL_STATE(43)] = 863,
  [SMALL_STATE(44)] = 876,
  [SMALL_STATE(45)] = 889,
  [SMALL_STATE(46)] = 902,
  [SMALL_STATE(47)] = 915,
  [SMALL_STATE(48)] = 928,
  [SMALL_STATE(49)] = 941,
  [SMALL_STATE(50)] = 954,
  [SMALL_STATE(51)] = 967,
  [SMALL_STATE(52)] = 980,
  [SMALL_STATE(53)] = 993,
  [SMALL_STATE(54)] = 1006,
  [SMALL_STATE(55)] = 1019,
  [SMALL_STATE(56)] = 1032,
  [SMALL_STATE(57)] = 1041,
  [SMALL_STATE(58)] = 1054,
  [SMALL_STATE(59)] = 1062,
  [SMALL_STATE(60)] = 1072,
  [SMALL_STATE(61)] = 1082,
  [SMALL_STATE(62)] = 1092,
  [SMALL_STATE(63)] = 1102,
  [SMALL_STATE(64)] = 1112,
  [SMALL_STATE(65)] = 1122,
  [SMALL_STATE(66)] = 1130,
  [SMALL_STATE(67)] = 1140,
  [SMALL_STATE(68)] = 1150,
  [SMALL_STATE(69)] = 1160,
  [SMALL_STATE(70)] = 1170,
  [SMALL_STATE(71)] = 1180,
  [SMALL_STATE(72)] = 1190,
  [SMALL_STATE(73)] = 1200,
  [SMALL_STATE(74)] = 1210,
  [SMALL_STATE(75)] = 1220,
  [SMALL_STATE(76)] = 1230,
  [SMALL_STATE(77)] = 1238,
  [SMALL_STATE(78)] = 1248,
  [SMALL_STATE(79)] = 1258,
  [SMALL_STATE(80)] = 1268,
  [SMALL_STATE(81)] = 1278,
  [SMALL_STATE(82)] = 1288,
  [SMALL_STATE(83)] = 1295,
  [SMALL_STATE(84)] = 1302,
  [SMALL_STATE(85)] = 1309,
  [SMALL_STATE(86)] = 1316,
  [SMALL_STATE(87)] = 1323,
  [SMALL_STATE(88)] = 1330,
  [SMALL_STATE(89)] = 1337,
  [SMALL_STATE(90)] = 1344,
  [SMALL_STATE(91)] = 1351,
  [SMALL_STATE(92)] = 1358,
  [SMALL_STATE(93)] = 1365,
  [SMALL_STATE(94)] = 1372,
  [SMALL_STATE(95)] = 1379,
  [SMALL_STATE(96)] = 1386,
  [SMALL_STATE(97)] = 1393,
  [SMALL_STATE(98)] = 1400,
  [SMALL_STATE(99)] = 1407,
  [SMALL_STATE(100)] = 1414,
  [SMALL_STATE(101)] = 1421,
  [SMALL_STATE(102)] = 1428,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__blank_lines, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__blank_lines, 2, 0, 0), SHIFT_REPEAT(2),
  [16] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 4, 0, 5),
  [18] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [20] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [22] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_feature, 4, 0, 5), SHIFT(2),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 5, 0, 7),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_feature, 5, 0, 7), SHIFT(2),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 5, 0, 5),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 6, 0, 7),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_block, 5, 0, 11),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scenario_block_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scenario_block_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_block, 8, 0, 14),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_provides_block, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_consumes_block, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_invariants_block, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_invariants_block_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_invariants_block_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_provides_block_repeat1, 2, 0, 0),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_provides_block_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_out_of_scope_block, 3, 0, 0),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_provides_block_repeat1, 2, 0, 0), SHIFT(2),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_invariants_block_repeat1, 2, 0, 0), SHIFT(2),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scenario_block_repeat1, 2, 0, 0), SHIFT(2),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 7, 0, 7),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier_path, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_feature_repeat2, 2, 0, 0),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_repeat2, 2, 0, 0), SHIFT_REPEAT(78),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 6, 0, 5),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_frontmatter_repeat1, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier_path, 2, 0, 0),
  [127] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_identifier_path_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_identifier_path_repeat1, 2, 0, 0),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_frontmatter_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 1),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 2),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(101),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 1),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 3),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 3, 0, 5),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_feature, 3, 0, 5), SHIFT(3),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 2),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 6),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 3),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_handle_entry, 2, 0, 8),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 4, 0, 7),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_feature, 4, 0, 7), SHIFT(4),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 6),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_path_handle, 1, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefixed_handle, 3, 0, 12),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [240] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry_description, 1, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_handle_entry, 3, 0, 10),
  [246] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_step_keyword, 1, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_name, 1, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter_entry, 3, 0, 4),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prose_text, 1, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prose_entry, 2, 0, 9),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step_text, 1, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step, 2, 0, 13),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_trellis(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "trellis",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
